- name: GitHub Webhook Listener
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Trigger Job on Push
      condition: event.payload.repository.name == "eda"
      action:
        run_job_template:
          name: eda-template
          organization: Default
